<a href="https://colab.research.google.com/github/annjerinsundar-code/ICTAK-AI-ML-Coursework/blob/main/NumPy_Array_Operations_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a NumPy array of shape (5, 5) with random integers between 1 and 50.

o Find the row with the maximum sum.

o Replace all elements greater than the mean with 0.

In [16]:
import numpy as np

# Create a 5 × 5 array with random integers from 1 to 50
arr = np.random.randint(1, 51, size=(5, 5))

print("Original Array:")
print(arr)

# Find the sum of each row
row_sums = np.sum(arr, axis=1)

# Find the row with the maximum sum
max_row = np.argmax(row_sums)

print("\nRow sums:")
print(row_sums)

print("\nRow with maximum sum:")
print(arr[max_row])

# Calculate the mean of the array
mean = np.mean(arr[max_row])

print("\nMean of row with maximum sum:", mean)

# Replace all elements greater than the mean, with 0, in the original array
arr[arr > mean] = 0

print("\nArray after replacing elements greater than mean with 0:")
print(arr)

Original Array:
[[ 5  8 47 28 10]
 [41 19 44 19 36]
 [45 37  9 24 49]
 [47 10 40 32 36]
 [32 11 16 40  5]]

Row sums:
[ 98 159 164 165 104]

Row with maximum sum:
[47 10 40 32 36]

Mean of row with maximum sum: 33.0

Array after replacing elements greater than mean with 0:
[[ 5  8  0 28 10]
 [ 0 19  0 19  0]
 [ 0  0  9 24  0]
 [ 0 10  0 32  0]
 [32 11 16  0  5]]
